FROM spark:python3

USER root

RUN apt -y install python3 pip
RUN pip install pandas pyarrow
RUN pip install pyspark --timeout 120 --retries 5

LABEL author="BD-UDESA-processing"
LABEL description="Imagen de Spark con pyspark"
LABEL version="1.0"
